[package]
name = "flat_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.7"
reqwest = { version = "0.11", features = ["blocking", "cookies"] }
scraper = "0.12.0"